export const testimonials = [
  {
    name: "Alexandre P.",
    role: "Entrepreneur",
    avatar: "AP",
    text: "Une expertise et une réactivité hors pair pour la création de notre société. Maître Bruveau a su nous guider à chaque étape avec clarté et professionnalisme.",
  },
  {
    name: "Marie & Jean D.",
    role: "Acquéreurs immobiliers",
    avatar: "MD",
    text: "L'accompagnement pour notre premier achat a été exceptionnel. Nous nous sommes sentis en totale confiance. Un grand merci pour votre patience et vos conseils avisés.",
  },
  {
    name: "Sophie L.",
    role: "Héritière",
    avatar: "SL",
    text: "La gestion de la succession a été menée avec beaucoup de tact et d'efficacité dans un moment difficile. Je recommande vivement le cabinet.",
  },
  {
    name: "Thomas R.",
    role: "Chef d'entreprise",
    avatar: "TR",
    text: "Très satisfait de la gestion de notre bail commercial. L'approche de Maître Bruveau est à la fois rigoureuse et pragmatique. Une collaboration efficace.",
  },
  {
    name: "Chloé B.",
    role: "Vendeuse d'un appartement",
    avatar: "CB",
    text: "Maître Bruveau a rendu la vente de mon appartement simple et fluide. Tout a été parfaitement expliqué et géré dans les temps. Je suis très reconnaissante.",
  },
  {
    name: "Julien M.",
    role: "Créateur de start-up",
    avatar: "JM",
    text: "Un conseil précieux pour la rédaction de nos statuts et notre pacte d'associés. L'étude a parfaitement compris nos enjeux et a su nous proposer des solutions adaptées.",
  },
  {
    name: "Famille Dubois",
    role: "Donation-partage",
    avatar: "FD",
    text: "Une écoute attentive et des conseils très humains pour organiser la transmission de notre patrimoine. Nous avons apprécié la pédagogie et la disponibilité de l'étude.",
  },
  {
    name: "Isabelle G.",
    role: "Divorce par consentement mutuel",
    avatar: "IG",
    text: "La procédure a été gérée avec une grande efficacité et discrétion. Maître Bruveau a su créer un climat de confiance, ce qui a grandement facilité les choses.",
  },
  {
    name: "Marc V.",
    role: "Investisseur immobilier",
    avatar: "MV",
    text: "Je confie toutes mes acquisitions à l'étude les yeux fermés. La sécurité juridique est totale et la réactivité est toujours au rendez-vous. Un partenaire de confiance.",
  },
  {
    name: "Laura S.",
    role: "Contrat de mariage",
    avatar: "LS",
    text: "Nous avons été très bien conseillés pour notre contrat de mariage. Les explications étaient claires et nous ont permis de faire un choix éclairé pour notre avenir.",
  },
  {
    name: "Patrick F.",
    role: "Gérant de SCI",
    avatar: "PF",
    text: "L'étude gère notre SCI familiale avec beaucoup de sérieux. Le suivi juridique est impeccable et les conseils sont toujours pertinents.",
  },
  {
    name: "Elodie T.",
    role: "Acquisition en VEFA",
    avatar: "ET",
    text: "Un grand merci pour l'accompagnement lors de notre achat sur plan. Nous avons été rassurés et guidés à chaque étape de ce projet important.",
  },
  {
    name: "Benoît C.",
    role: "Entrepreneur individuel",
    avatar: "BC",
    text: "Passage en société, cession de fonds de commerce... Maître Bruveau m'a accompagné dans toutes les évolutions de mon activité avec une grande compétence.",
  },
  {
    name: "Anne-Sophie P.",
    role: "Gestion de patrimoine",
    avatar: "AP",
    text: "Une approche très professionnelle et globale de la gestion de patrimoine. La collaboration avec Maître Couzigou-Suhas est un vrai plus.",
  },
  {
    name: "David L.",
    role: "Succession internationale",
    avatar: "DL",
    text: "Un dossier complexe de succession avec des biens à l'étranger qui a été géré avec une maîtrise parfaite. Je ne peux que recommander cette étude.",
  },
  {
    name: "Stéphanie M.",
    role: "Mise en copropriété",
    avatar: "SM",
    text: "La création de la copropriété de notre immeuble a été un long processus, mais l'étude a su le mener à bien avec patience et rigueur. Excellent travail.",
  },
  {
    name: "Olivier H.",
    role: "Restructuration d'entreprise",
    avatar: "OH",
    text: "L'expertise de Maître Bruveau en droit des sociétés a été déterminante dans le succès de notre opération de fusion. Un partenaire de haut niveau.",
  },
  {
    name: "Nathalie R.",
    role: "Adoption",
    avatar: "NR",
    text: "Un moment émouvant et important de notre vie, géré avec beaucoup de délicatesse et d'humanité par l'étude. Nous vous remercions chaleureusement.",
  },
  {
    name: "François G.",
    role: "Promoteur immobilier",
    avatar: "FG",
    text: "Je travaille régulièrement avec l'étude pour mes programmes. La fiabilité et l'efficacité sont constantes. C'est un plaisir de collaborer ensemble.",
  },
  {
    name: "Céline et Paul V.",
    role: "Acquéreurs avec prêt relais",
    avatar: "CP",
    text: "Notre situation était complexe, mais l'étude a su trouver les solutions et parfaitement coordonner la vente et le nouvel achat. Un immense soulagement !",
  },
  {
    name: 'Antoine B.',
    role: 'Artisan',
    avatar: 'AB',
    text: 'Grâce à Maître Bruveau, j\'ai pu protéger mon patrimoine personnel en choisissant la bonne structure juridique. Ses conseils ont été précieux.',
  },
  {
    name: 'Camille L.',
    role: 'Jeune couple',
    avatar: 'CL',
    text: 'Notre premier achat immobilier s\'est déroulé sans aucun stress grâce à la clarté et à la disponibilité de toute l\'équipe. Un immense merci !',
  },
  {
    name: 'Georges T.',
    role: 'Retraité',
    avatar: 'GT',
    text: 'Pour ma donation à mes enfants, tout a été expliqué simplement. J\'ai apprécié la pédagogie et la patience de Maître Bruveau.',
  },
  {
    name: 'Hélène F.',
    role: 'Commerçante',
    avatar: 'HF',
    text: 'La cession de mon fonds de commerce a été gérée de main de maître. Une transaction rapide, efficace et sécurisée.',
  },
  {
    name: 'Lucas P.',
    role: 'Expatrié',
    avatar: 'LP',
    text: 'Même à distance, la gestion de mes affaires en France a été impeccable. La communication est fluide et la réactivité est exemplaire.',
  },
  {
    name: 'Margot C.',
    role: 'Famille recomposée',
    avatar: 'MC',
    text: 'Maître Bruveau nous a aidés à organiser notre situation familiale complexe avec beaucoup de tact et des solutions juridiques adaptées.',
  },
  {
    name: 'Nicolas D.',
    role: 'Investisseur',
    avatar: 'ND',
    text: 'L\'analyse des risques et la rédaction des actes pour mes investissements locatifs sont toujours d\'une qualité irréprochable. Je recommande.',
  },
  {
    name: 'Pauline R.',
    role: 'Donatrice',
    avatar: 'PR',
    text: 'Un accompagnement rempli d\'humanité et de professionnalisme pour la transmission d\'un bien qui me tenait à cœur.',
  },
  {
    name: 'Quentin S.',
    role: 'Dirigeant PME',
    avatar: 'QS',
    text: 'L\'étude nous accompagne sur tous nos sujets de droit des sociétés. C\'est un véritable partenaire de notre croissance.',
  },
  {
    name: 'Raphaël V.',
    role: 'Acquéreur en indivision',
    avatar: 'RV',
    text: 'Les conseils pour notre achat en indivision ont été très clairs et nous ont permis d\'éviter les pièges. Très professionnel.',
  },
  {
    name: 'Sylvie M.',
    role: 'Testament',
    avatar: 'SM',
    text: 'J\'ai été rassurée et parfaitement conseillée pour la rédaction de mon testament. Un service discret et de grande qualité.',
  },
  {
    name: 'Thierry G.',
    role: 'Vente d\'un terrain',
    avatar: 'TG',
    text: 'Le dossier était complexe avec des questions d\'urbanisme, mais l\'étude a tout géré avec une grande expertise. Très satisfait.',
  },
  {
    name: 'Valérie B.',
    role: 'Créatrice d\'entreprise',
    avatar: 'VB',
    text: 'Un soutien sans faille lors du lancement de mon projet. L\'étude a été bien plus qu\'un simple notaire, un vrai conseiller.',
  },
  {
    name: 'William N.',
    role: 'Partage de biens',
    avatar: 'WN',
    text: 'Le partage suite à notre séparation a été mené de manière équitable et apaisée grâce à l\'intervention de Maître Bruveau.',
  },
  {
    name: 'Xavier L.',
    role: 'Bailleur',
    avatar: 'XL',
    text: 'La rédaction de mes baux commerciaux par l\'étude me garantit une tranquillité d\'esprit. Un service indispensable.',
  },
  {
    name: 'Yasmine A.',
    role: 'Héritière',
    avatar: 'YA',
    text: 'Merci pour votre soutien et votre efficacité dans le règlement de la succession de mon père. Votre aide a été précieuse.',
  },
  {
    name: 'Zoé K.',
    role: 'Future mariée',
    avatar: 'ZK',
    text: 'Les explications sur les différents régimes matrimoniaux nous ont permis de choisir en toute connaissance de cause. Parfait !',
  },
  {
    name: 'Arnaud L.',
    role: 'Dirigeant d\'association',
    avatar: 'AL',
    text: 'L\'étude nous a conseillés pour la mise à jour de nos statuts. Un travail rapide et précis.',
  },
  {
    name: 'Béatrice P.',
    role: 'Vente en viager',
    avatar: 'BP',
    text: 'Un sujet délicat abordé avec beaucoup de professionnalisme et de clarté. Je me suis sentie en confiance du début à la fin.',
  },
  {
    name: 'Charles E.',
    role: 'Chef de projet',
    avatar: 'CE',
    text: 'Collaboration très efficace pour un projet de promotion immobilière. L\'expertise de l\'étude est un atout majeur.',
  },
  {
    name: 'Delphine M.',
    role: 'Acquéreur primo-accédant',
    avatar: 'DM',
    text: 'En tant que primo-accédants, nous avions beaucoup de questions. L\'équipe a été d\'une patience et d\'une pédagogie remarquables.',
  },
  {
    name: 'Eric S.',
    role: 'Gestionnaire de fortune',
    avatar: 'ES',
    text: 'Je fais appel à Maître Bruveau pour les aspects notariaux des dossiers de mes clients. La collaboration est toujours fluide et de grande qualité.',
  },
  {
    name: 'Florence A.',
    role: 'Mandat de protection future',
    avatar: 'FA',
    text: 'Nous avons mis en place un mandat de protection future pour mes parents. Les conseils de l\'étude ont été essentiels pour nous guider.',
  },
  {
    name: 'Gaspard D.',
    role: 'Photographe',
    avatar: 'GD',
    text: 'Pour la création de ma société d\'auteur, j\'ai trouvé un interlocuteur qui a parfaitement compris les spécificités de mon activité.',
  },
  {
    name: 'Inès R.',
    role: 'Vente d\'une maison de famille',
    avatar: 'IR',
    text: 'Un contexte émotionnel fort, géré avec beaucoup de respect et de professionnalisme par Maître Bruveau et son équipe.',
  },
  {
    name: 'Jean-Christophe B.',
    role: 'Agriculteur',
    avatar: 'JB',
    text: 'L\'étude m\'a accompagné pour la création d\'un GFA. Une expertise pointue sur le droit rural que j\'ai beaucoup appréciée.',
  },
  {
    name: 'Karine V.',
    role: 'Divorce',
    avatar: 'KV',
    text: 'Maître Bruveau a su trouver les mots justes et les solutions juridiques pour que notre divorce se passe au mieux. Je la remercie.',
  },
  {
    name: 'Léo Z.',
    role: 'Étudiant investisseur',
    avatar: 'LZ',
    text: 'Mon premier investissement locatif a été une réussite grâce aux conseils avisés de l\'étude pour sécuriser l\'opération.',
  },
  {
    name: 'Mélanie H.',
    role: 'Famille',
    avatar: 'MH',
    text: 'Nous avons fait appel à l\'étude pour plusieurs étapes de notre vie (achat, contrat de mariage, testament). C\'est notre notaire de famille.',
  },
  {
    name: 'Noémie C.',
    role: 'Profession libérale',
    avatar: 'NC',
    text: 'Installation, création de SCM, bail professionnel... L\'étude a été présente à chaque moment clé de mon installation.',
  },
  {
    name: 'Pascal T.',
    role: 'Vendeur',
    avatar: 'PT',
    text: 'Efficacité et rapidité. La vente de mon bien s\'est faite dans des conditions optimales. Je recommande sans hésiter.',
  },
  {
    name: 'Romain F.',
    role: 'Père de famille',
    avatar: 'RF',
    text: 'Nous avons mis en place une donation pour nos enfants. Tout était très clair et bien organisé. Un grand professionnalisme.',
  },
  {
    name: 'Sandrine J.',
    role: 'Acquéreur',
    avatar: 'SJ',
    text: 'Une disponibilité et une réactivité très appréciables. L\'étude a facilité toutes les démarches de notre acquisition.',
  },
  {
    name: 'Sébastien G.',
    role: 'Investisseur étranger',
    avatar: 'SG',
    text: 'L\'étude a parfaitement géré mon investissement immobilier en France, malgré la distance. Une communication excellente.',
  },
  {
    name: 'Tatiana L.',
    role: 'Chef d\'orchestre',
    avatar: 'TL',
    text: 'Pour la gestion de mes droits, j\'avais besoin d\'un conseil pointu. Je l\'ai trouvé auprès de Maître Bruveau.',
  },
  {
    name: 'Victor M.',
    role: 'Héritier',
    avatar: 'VM',
    text: 'La succession a été traitée avec une grande rapidité et efficacité. L\'équipe est très professionnelle et à l\'écoute.',
  },
  {
    name: 'Amélie N.',
    role: 'Jeune entrepreneure',
    avatar: 'AN',
    text: 'Un accompagnement au top pour le lancement de ma première entreprise. Je me suis sentie épaulée et en sécurité sur le plan juridique.',
  },
  {
    name: 'Benjamin R.',
    role: 'Couple pacsé',
    avatar: 'BR',
    text: 'Nous avons été très bien informés sur les implications du PACS et la rédaction de notre testament. Merci pour votre pédagogie.',
  },
  {
    name: 'Clara D.',
    role: 'Vendeuse d\'un local commercial',
    avatar: 'CD',
    text: 'Transaction complexe menée avec brio. La compétence et la ténacité de l\'étude ont été déterminantes.',
  },
];
